version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    environment:
      COURSES_PATH: /app/data/courses.json
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: celery -A backend.app.celery_app.celery_app worker --loglevel=info
    env_file:
      - .env
    environment:
      COURSES_PATH: /app/data/courses.json
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - ./:/app
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    command: npm run dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      - frontend-node_modules:/app/node_modules
      - frontend-next-cache:/app/.next
    ports:
      - "8080:3000"
    environment:
      NEXT_PUBLIC_API_BASE: /api
      API_PROXY_TARGET: http://backend:8000
      CHOKIDAR_USEPOLLING: "1"
      WATCHPACK_POLLING: "true"
    depends_on:
      - backend
    tty: true
    stdin_open: true

  # GitHub Pages preview server
  github-pages:
    image: nginx:1.27-alpine
    volumes:
      - ./docs:/usr/share/nginx/html:ro
      - ./nginx-github-pages.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "3000:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  frontend-node_modules:
  frontend-next-cache:
