version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    environment:
      COURSES_PATH: /app/data/courses.json
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: celery -A backend.app.celery_app.celery_app worker --loglevel=info
    env_file:
      - .env
    environment:
      COURSES_PATH: /app/data/courses.json
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - ./:/app
    depends_on:
      - redis

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

  # GitHub Pages preview server
  github-pages:
    image: nginx:1.27-alpine
    volumes:
      - ./github-pages:/usr/share/nginx/html:ro
      - ./nginx-github-pages.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "3000:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
