blank_issues_enabled: true
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/davidlarrimore/ai-training-catalog/discussions
    about: Ask questions and discuss with the community
  - name: 📚 Browse Catalog
    url: https://davidlarrimore.github.io/ai-training-catalog/
    about: Browse the course catalog online
  - name: 📖 Documentation
    url: https://github.com/davidlarrimore/ai-training-catalog/blob/main/README.md
    about: Read the project documentation
