title: AI Training List
description: Curated list of online AI training resources
# Minimal is a supported Pages theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
# Optional tweaks
logo: ./favicon-32x32.png
show_downloads: false
# Optional tweaks